### ISSUE TITLE
Generating discount codes for reviews left on w.org is not okay...

### ISSUE THREAD

**Issue by Otto42** [julien731/WP-Review-Me#3]
Please remove the EDD integration and do not support this functionality.

Any theme or plugin found using this type of functionality to provide incentives, of any kind, for leaving reviews on WordPress.org will be subject to penalties such as:
- Having all their reviews removed
- Having their plugin or theme removed
- Banning their account from WordPress.org

It is NOT okay to offer to pay for reviews. Even if that pay is merely in the form of a discount. 

_Asking_ for a review is fine. _Paying_ for it is not.

Think of it like this: Regardless of whether you say that you will still give a discount even for a "bad" review, the result is that people don't really believe that. Therefore, any form of compensation for reviews leads to a greater proportion of "good" reviews, skewing the results. You are therefore paying people to leave potentially false or misleading reviews, and on a site that is not your own as well. 

It's like restaurants paying people to leave good reviews on Yelp. It's just not okay no matter how you slice it.

If this type of functionality is included in this library, then the library will need to be added to our scanners so that we can disallow it from being included in any plugin or theme in the WordPress.org directories.

**Comment by julien731** [comment]
Quite a virulent way of expressing it but I guess I understand.

My point of view was probably naive as I was thinking this would just push satisfied users who don't review to actually review a plugin/theme. Honestly, it didn't cross my mind that people would leave reviews that don't match their actual experience. But I get it.

I think we all know that unsatisfied users are always the first to leave a bad review while satisfied users often don't say anything. I saw this as a way of encouraging satisfied users to not just skip it.

Also, it is quite a common practice to give clients a discount/advantage in exchange for marketing material in many industries.

With all that said, I don't want to go against the .org rules so sure I will remove this part. This will, obviously, close issue #2 as well.

**Comment by Otto42** [comment]
Sorry for the harsh tone. We've had to deal with some really shady situations in the w.org forums, especially with regards to reviews, so perhaps I'm just jaded a bit there. :)

The truth of the matter is that WordPress.org, as a community site, isn't a place for you to do your marketing. I understand that is how a lot of people see it, especially with the notion of up-selling free plugins and the like, but that's not how we see it and it's not how we want you to see it either.

WordPress.org is the hub of the community, where we come together in order to help people, to make free and open-source software, and to give away our own creations for others to use. 

The plugin/theme directories are not an app-store. It's not a way to connect "developers" with "customers", it's a way to connect "users who write code" with "users who use that code". Equality, basically. The whole "upsell" thing, while totally permissible and reasonable, isn't the primary focus. So, when we see things like people paying others to essentially spam the forums with reviews in order for them to achieve gain for themselves instead of to help out their other fellow users, well.. I'm sure you can understand my reaction. (And you may totally object to my use of the word "spam" there, and I understand that objection fully, but.. just calling it like I see it.)

Encouraging users to leave a review is a good idea, and many plugins do this already, and we love it. It's great. _Paying_ them to leave reviews, not so much. It's very bad, leads to lots of "spam" in our systems, angry people emailing us about all the fake reviews, etc. We already have a minor fake review problem. We don't want to make it even worse. The reviews should be, above all else, useful to others. We're working on ways to improve their usefulness, to surface the best reviews and hide the junk ones. Things like that. Adding more junk in there, not helpful. 

Glad you understand. :)

Oh, one more thing: What's the point of having a rating system when everybody is working like crazy to fill it with useless 5 star reviews only? If a rating system has everything rated at 4.8 stars, then the ratings are completely worthless. Real systems, with real ratings, by real people, should have a range. This isn't eBay. Don't be discouraged by a 3.9 rating. That's what you get in a _normal_ system that is working correctly. :)

**Comment by julien731** [comment]
Well yeah. I do understand. I think you're right in saying that wp.org is not a place for doing marketing. I have to admit that I didn't really think about it this way.

Again, the last thing I want to do is go against the .org guidelines. I'll be removing this feature from the library shortly. Thanks for replying back on this issue.

Lastly, is the "timer" thing [pointed out by Emil on the FB topic](https://www.facebook.com/groups/advancedwp/permalink/1139490606113152/?comment_id=1139742779421268&comment_tracking=%7B%22tn%22%3A%22R3%22%7D) okay?

**Comment by Otto42** [comment]
Timer thing doesn't bug me as long as it's dismissable. As in "go away I don't want to see this ever again" type of dismissable. Users would probably leave you bad reviews for having an annoying nag screen, but that's neither here nor there.

**Comment by julien731** [comment]
Of course. I hate non-dismissible notices. I actually wrote a small library for that as well which is used in this one for dismissal and based on `.is-dismissible` of WordPress 4.2+: https://github.com/julien731/WP-Dismissible-Notices-Handler

**Comment by maximejobin** [comment]
@julien731 - I know this thread is now closed but I wanted to add that you should always comply with what w.org asks you, even if you respected the established rules.  Challenging these folks may result in adding new rules or bending them by adding a "point of clarification" in order to ban you permanently.  They are free to do it (as in free beer and free speech... well, wrong example).

And don't ask why JetPack can do things that go against the rules... it's useless.

Yeah... it happened to me.  You don't want that.

P.S. Great project you have!  Not enough people give reviews. Good thing you encourage them! :+1:
