### ISSUE TITLE
Wrong url for the review

### ISSUE THREAD

**Issue by Mte90** [julien731/WP-Review-Me#4]
Actually this is the link generated https://wordpress.org/support/view/plugin-reviews/datask?rate=5#postform
But as i can see from the plugin page now is https://wordpress.org/support/plugin/datask/reviews/?rate=5#new-post

**Comment by julien731** [comment]
Indeed the reviews URL has changed on WordPress.org. Thanks for pointing it out.

**Comment by Mte90** [comment]
any chance for a update?

**Comment by julien731** [comment]
Sorry for the delay. URLs updated now.
